### ISSUE TITLE
error when I involk `:DevdocsInstall`

### ISSUE THREAD

**Issue by Song-Tianxiang** [girishji/devdocs.vim#1] opened 2024-03-08 16:12 UTC
I have installed plugin, and do `:DevdocsInstall` get 
```
Error detected while processing /Users/donotreason/.vim/pack/downloads/opt/devdocs.vim/autoload/devdocs/install.vim:
line    4:
E1053: Could not import "./popup.vim"
E1048: Item not found in script: Install
```

**Comment by ttkap** [comment] 2024-03-08 16:28
For me `:DevdocsInstall` does not give any error. I can see the menu an select some item.
But `:DevdocsFind` gives a similar error though:
```
Error detected while processing /home/****/.vim/pack/downloads/opt/devdocs.vim/autoload/devdocs/find.vim:
line    3:
E1053: Could not import "./popup.vim"
E1048: Item not found in script: Find
```
reproduction step: empty `.vimrc` file with just a single line: `packadd devdocs.vim`

**Comment by Song-Tianxiang** [comment] 2024-03-08 16:38
all `Devdocs*` gives me similar error. vim version: 9.1.100. `scope.vim` gives the error too
```
Error detected while processing /Users/donotreason/.vim/.data/plug/scope.vim/autoload/scope/fuzzy.vim:
line    4:
E1053: Could not import "./popup.vim"
E1048: Item not found in script: File
```

**Comment by girishji** [comment] 2024-03-09 07:33
Can you upgrade and try again?

I could not reproduce on macos. Is this happening on windows/linux? Anyway I forced lazy loading. Let's see if it fixes.

**Comment by ttkap** [comment] 2024-03-09 08:40
It is on linux (ubuntu 22.04)
Now I have a different error.
```
Error detected while processing function devdocs#find#Find[14]..<SNR>19_ShowMenu:
line   10:
E1048: Item not found in script: devdocs#popup#FilterMenu
```

Might be worth mentionning also that when i use `:DevdocsInstall` and install for example `numpy~1.23` it is installed in a directory named `numpy~1.23.tmp/` inside `~/.local/share/devdocs/` and the files are` 'db.json?1664829125' `, `'index.json?1664829125'` which seems weird ?

**Comment by DanielViberg** [comment] 2024-03-09 09:04
I can confirm, default installation i get:
![image](https://github.com/girishji/devdocs.vim/assets/27137435/fa430834-153e-4591-af46-6d957ebfc9b1)

**Comment by Song-Tianxiang** [comment] 2024-03-09 09:22
Actually, I can solve this problem by rename popup.vim to pop.vim and `import './pop.vim' as popup` in install.vim. It's really weird.

**Comment by girishji** [comment] 2024-03-09 10:57
I reproduced the problem. It is a bug in vim9 import mechanism. Fix coming soon.

**Comment by girishji** [comment] 2024-03-09 11:23
Try it now.

I am heading out for a few hrs. I may change some more things when I come back, so this is a quick fix.

**Comment by girishji** [comment] 2024-03-09 14:18
I am closing this. It should be fixed. If you still have this error please reopen the issue.

**Closed as completed** 2024-03-09 14:19 UTC

**Comment by DanielViberg** [comment] 2024-03-09 14:56
![output](https://github.com/girishji/devdocs.vim/assets/27137435/61cdd2f6-0150-4538-a8b4-fd4cc1a8f25e)
Dowloading the doc seems to work, but using the find function does not.

**Comment by girishji** [comment] 2024-03-09 16:49
Can you check `~/.local/share/devdocs` and see if the lugs are there. I do not see the 'success' message echoed in command line.  Did you type `<c-c`>?

It creates a .tmp directory, unpacks and then does `mv`. Maybe permissions issue? It should print a error message in any case, so I am surprised.

**Comment by DanielViberg** [comment] 2024-03-09 19:33
I typed nothing, the popup was removed by itself. 
It seems populated: 
![image](https://github.com/girishji/devdocs.vim/assets/27137435/d3167144-bc4a-4aef-a543-75d0bc667f7b)

**Comment by ttkap** [comment] 2024-03-09 20:57
> Might be worth mentionning also that when i use `:DevdocsInstall` and install for example `numpy~1.23` it is installed in a directory named `numpy~1.23.tmp/` inside `~/.local/share/devdocs/` and the files are`'db.json?1664829125'`, `'index.json?1664829125'` which seems weird ?

Yes indeed, see my previous comment above. It seems the installation process does not go through the end. html files are not created.

**Comment by girishji** [comment] 2024-03-10 06:25
Looks like issue related to few specific slugs from devdocs.io CDN. thanks for fixing.

**Comment by DanielViberg** [comment] 2024-03-10 08:45
Installation now seems to work, thanks!
